# Generated by Django 3.2.3 on 2021-12-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('none', 'Prefer Not To Say')], default='none', max_length=25),
        ),
    ]
