# Generated by Django 3.2.3 on 2022-02-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211217_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing',
            name='img',
            field=models.ImageField(default='media/missing-people/park.JPG', upload_to='missing-people/'),
        ),
        migrations.AddField(
            model_name='missing',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
