# Generated by Django 3.2.3 on 2022-02-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220208_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing',
            name='img',
            field=models.ImageField(default='media/missing-people/park.JPG', upload_to='media/missing-people/'),
        ),
    ]
