# Generated by Django 3.2.3 on 2022-02-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_missing_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missing',
            old_name='img',
            new_name='img_person',
        ),
    ]
